// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package org.apache.dolphinscheduler.rpc;

public interface PathParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schduler.PathParameter)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * path
   * </pre>
   *
   * <code>string path = 1;</code>
   */
  java.lang.String getPath();
  /**
   * <pre>
   **
   * path
   * </pre>
   *
   * <code>string path = 1;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();
}
