// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package org.apache.dolphinscheduler.rpc;

public interface RetStrInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:schduler.RetStrInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   *  str msg info
   * </pre>
   *
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <pre>
   **
   *  str msg info
   * </pre>
   *
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
