// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheduler.proto

package org.apache.dolphinscheduler.rpc;

public final class SchdulerProto {
  private SchdulerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schduler_RetStrInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schduler_RetStrInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schduler_RetByteInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schduler_RetByteInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schduler_LogParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schduler_LogParameter_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_schduler_PathParameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_schduler_PathParameter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017scheduler.proto\022\010schduler\"\031\n\nRetStrInf" +
      "o\022\013\n\003msg\030\001 \001(\t\"\033\n\013RetByteInfo\022\014\n\004data\030\001 " +
      "\001(\014\"@\n\014LogParameter\022\014\n\004path\030\001 \001(\t\022\023\n\013ski" +
      "pLineNum\030\002 \001(\005\022\r\n\005limit\030\003 \001(\005\"\035\n\rPathPar" +
      "ameter\022\014\n\004path\030\001 \001(\t2\314\001\n\016LogViewService\022" +
      "=\n\013rollViewLog\022\026.schduler.LogParameter\032\024" +
      ".schduler.RetStrInfo\"\000\022:\n\007viewLog\022\027.schd" +
      "uler.PathParameter\032\024.schduler.RetStrInfo" +
      "\"\000\022?\n\013getLogBytes\022\027.schduler.PathParamet" +
      "er\032\025.schduler.RetByteInfo\"\000B2\n\037org.apach" +
      "e.dolphinscheduler.rpcB\rSchdulerProtoP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_schduler_RetStrInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_schduler_RetStrInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schduler_RetStrInfo_descriptor,
        new java.lang.String[] { "Msg", });
    internal_static_schduler_RetByteInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_schduler_RetByteInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schduler_RetByteInfo_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_schduler_LogParameter_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_schduler_LogParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schduler_LogParameter_descriptor,
        new java.lang.String[] { "Path", "SkipLineNum", "Limit", });
    internal_static_schduler_PathParameter_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_schduler_PathParameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_schduler_PathParameter_descriptor,
        new java.lang.String[] { "Path", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
